# K-Nearest-Neighbors (KNN)


## Importing Libraries

In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

#Importing the data
## About the data

<img src='https://images.squarespace-cdn.com/content/v1/5c36736d9d5abb8b44c6b7f7/1586468701075-G14EXPZE2VNMJFKDCQ0T/rook+and+king+logo.jpg?format=500w' align="center"><br>
  Chess End-Game -- King+Rook versus King+Pawn on a7
  (usually abbreviated KRKPA7).  The pawn on a7 means it is one square
  away from queening.  It is the King+Rook's side (white) to move.

  

In [2]:
king_data=pd.read_excel('King-RookvsKing-Pawn.xlsx')

In [3]:
king_data.head(10)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0       f       f       f       f  ...        t        t        n      won
1       f       f       f       f  ...        t        t        n      won
2       f       f       f       f  ...        t        t        n      won
3       f       f       f       f  ...        t        t        n      won
4       f       f       f       f  ...        t        t        n      won
5       f       f       f       f  ...        t        t        n      won
6       f       f       f       f  ...        t        t        n      won
7       f       f       f       f  ...        t        t        n      won
8       f       f       f       f  ...        t        t        n      won
9       f       f       f       f  ...        t        t        n      won

[10 rows x 37 columns]

In [4]:
king_data.columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 'Column24',
       'Column25', 'Column26', 'Column27', 'Column28', 'Column29', 'Column30',
       'Column31', 'Column32', 'Column33', 'Column34', 'Column35', 'Column36',
       'Column37'],
      dtype='object')

In [5]:
object_col=['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 'Column24',
       'Column25', 'Column26', 'Column27', 'Column28', 'Column29', 'Column30',
       'Column31', 'Column32', 'Column33', 'Column34', 'Column35', 'Column36'
       ]

Droping NaN values

In [6]:
king_data.dropna(axis=0)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0          f       f       f       f  ...        t        t        n      won
1          f       f       f       f  ...        t        t        n      won
2          f       f       f       f  ...        t        t        n      won
3          f       f       f       f  ...        t        t        n      won
4          f       f       f       f  ...        t        t        n      won
...      ...     ...     ...     ...  ...      ...      ...      ...      ...
3191       t       f       f       f  ...        t        f        n    nowin
3192       t       f       f       f  ...        t        f        n    nowin
3193       t       f       f       f  ...        t        f        n    nowin
3194       t       f       t       f  ...        f        f        n    nowin
3195       t       f       t       f  ...        f        f        n    nowin

[3196 rows x 37 columns]

In [7]:
print(f'{king_data.Column37.unique()}')

['won' 'nowin']


In [8]:
king_data['Column37']=king_data['Column37'].apply({'won':2,'nowin':1}.get)

In [9]:
king_data.head(10)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0       f       f       f       f  ...        t        t        n        2
1       f       f       f       f  ...        t        t        n        2
2       f       f       f       f  ...        t        t        n        2
3       f       f       f       f  ...        t        t        n        2
4       f       f       f       f  ...        t        t        n        2
5       f       f       f       f  ...        t        t        n        2
6       f       f       f       f  ...        t        t        n        2
7       f       f       f       f  ...        t        t        n        2
8       f       f       f       f  ...        t        t        n        2
9       f       f       f       f  ...        t        t        n        2

[10 rows x 37 columns]

## Spliting the data.

In [10]:
X=king_data.copy()
y=X.pop('Column37')

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,train_size=0.3)


In [11]:
y_test.head(10)

362     2
3180    1
241     2
3049    1
550     2
2497    1
651     2
1903    2
2715    1
1459    1
Name: Column37, dtype: int64

## Training and predicting the model using KNN algo.



In [12]:
from sklearn.preprocessing import OneHotEncoder
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)

one_hot_train=pd.DataFrame(OH_encoder.fit_transform(X_train[object_col]))
one_hot_test=pd.DataFrame(OH_encoder.transform(X_test[object_col]))
one_hot_train.index = X_train.index
one_hot_test.index = X_test.index

In [13]:
num_X_train = X_train.drop(object_col, axis=1)
num_X_valid = X_test.drop(object_col, axis=1)

In [14]:
OH_X_train = pd.concat([num_X_train, one_hot_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, one_hot_test], axis=1)

In [15]:
y_train.unique()

array([2, 1])

In [16]:
from sklearn.neighbors import KNeighborsClassifier as knn

model=knn(n_neighbors=1,
          leaf_size=1,
          algorithm='brute',
          weights='distance',
          p=1
          )

model.fit(OH_X_train,y_train)

KNeighborsClassifier(algorithm='brute', leaf_size=1, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=1,
                     weights='distance')

In [17]:
pred=model.predict(OH_X_valid)

## Checking model accuracy.


In [18]:
from sklearn.metrics import accuracy_score

x=accuracy_score(y_test,pred)
print(f'the accuracy score is {x}')

the accuracy score is 0.8690795352993744


## Using confusion matric

In [19]:
from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_test,pred)

In [20]:
print(cm)

[[ 911  143]
 [ 150 1034]]


Random Forest Classifier 

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
rfc = RandomForestClassifier(n_jobs=-1, oob_score = True) 
param_grid = {  'n_estimators': [200,400,600, 800], 'max_features': ['auto', 'sqrt', 'log2'] }
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(OH_X_train,y_train)


GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=-1,
                                              oob_score=True, random_state=None,
                                   

In [22]:
print("\n best score:\n",CV_rfc.best_score_)
print("\n best parameters:\n",CV_rfc.best_params_)


 best score:
 0.9770287958115184

 best parameters:
 {'max_features': 'auto', 'n_estimators': 200}


In [23]:
model = RandomForestClassifier(n_jobs=-1, oob_score = True,max_features =  'log2',  n_estimators = 200 )
model.fit(OH_X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=-1, oob_score=True, random_state=None, verbose=0,
                       warm_start=False)

In [24]:
pred_rf=model.predict(OH_X_valid)

In [25]:
x_rf=accuracy_score(y_test,pred_rf)
print(f'the accuracy score is {x_rf}')

the accuracy score is 0.9812332439678284


In [41]:
cm= confusion_matrix(y_test,pred_rf)
print(cm)

[[1025   29]
 [  13 1171]]


Catboost

In [26]:

!pip3 install catboost

     |████████████████████████████████| 76.4 MB 21 kB/s 


In [27]:
from catboost import CatBoostClassifier

clf = CatBoostClassifier(iterations=100,  learning_rate=0.1)
clf.fit(OH_X_train,y_train)

0:	learn: 0.5590342	total: 51.1ms	remaining: 5.06s
1:	learn: 0.4603404	total: 55.2ms	remaining: 2.7s
2:	learn: 0.3835269	total: 59.2ms	remaining: 1.92s
3:	learn: 0.3303086	total: 61.5ms	remaining: 1.47s
4:	learn: 0.2916562	total: 65.3ms	remaining: 1.24s
5:	learn: 0.2560218	total: 69.4ms	remaining: 1.09s
6:	learn: 0.2323128	total: 73.4ms	remaining: 975ms
7:	learn: 0.2165856	total: 77.4ms	remaining: 890ms
8:	learn: 0.1987849	total: 81.3ms	remaining: 822ms
9:	learn: 0.1864985	total: 85.3ms	remaining: 767ms
10:	learn: 0.1742322	total: 89.1ms	remaining: 721ms
11:	learn: 0.1639353	total: 92.9ms	remaining: 681ms
12:	learn: 0.1573169	total: 96.8ms	remaining: 648ms
13:	learn: 0.1516665	total: 101ms	remaining: 619ms
14:	learn: 0.1476412	total: 105ms	remaining: 593ms
15:	learn: 0.1417165	total: 109ms	remaining: 570ms
16:	learn: 0.1376439	total: 120ms	remaining: 585ms
17:	learn: 0.1332262	total: 124ms	remaining: 566ms
18:	learn: 0.1297797	total: 128ms	remaining: 546ms
19:	learn: 0.1241627	total: 1

In [28]:
pred_cat=clf.predict(OH_X_valid)

In [29]:
from sklearn.metrics import accuracy_score
x_cat=accuracy_score(y_test,pred_cat)
print(f'the accuracy score is {x_cat}')

the accuracy score is 0.985254691689008


In [42]:
cm= confusion_matrix(y_test,pred_cat)
print(cm)

[[1038   16]
 [  17 1167]]


Multilayer Perceptron (MLP)

In [30]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='adam', activation='relu',alpha=0.0001,hidden_layer_sizes=(8,8,8), random_state=1,max_iter=421,verbose=10)
mlp.fit(OH_X_train,y_train)

Iteration 1, loss = 0.83328553
Iteration 2, loss = 0.79891767
Iteration 3, loss = 0.76655694
Iteration 4, loss = 0.74249841
Iteration 5, loss = 0.72776093
Iteration 6, loss = 0.71746493
Iteration 7, loss = 0.71142990
Iteration 8, loss = 0.70693251
Iteration 9, loss = 0.70186395
Iteration 10, loss = 0.69665016
Iteration 11, loss = 0.69097754
Iteration 12, loss = 0.68479880
Iteration 13, loss = 0.67806365
Iteration 14, loss = 0.67026380
Iteration 15, loss = 0.66121409
Iteration 16, loss = 0.65181514
Iteration 17, loss = 0.64116872
Iteration 18, loss = 0.62987951
Iteration 19, loss = 0.61740781
Iteration 20, loss = 0.60368160
Iteration 21, loss = 0.58927060
Iteration 22, loss = 0.57303158
Iteration 23, loss = 0.55410981
Iteration 24, loss = 0.53270231
Iteration 25, loss = 0.51057900
Iteration 26, loss = 0.48595406
Iteration 27, loss = 0.45917372
Iteration 28, loss = 0.43406225
Iteration 29, loss = 0.40952022
Iteration 30, loss = 0.38575846
Iteration 31, loss = 0.36393342
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8, 8, 8), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=421,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=10,
              warm_start=False)

In [31]:
pred_mlp=mlp.predict(OH_X_valid)

In [32]:
x_mlp=accuracy_score(y_test,pred_mlp)
print(f'the accuracy score is {x_mlp}')

the accuracy score is 0.9816800714924039


In [43]:
cm= confusion_matrix(y_test,pred_mlp)
print(cm)

[[1042   12]
 [  29 1155]]


Light GBM 

In [33]:
from lightgbm import LGBMClassifier
model_ = LGBMClassifier(n_estimators=100,num_leaves=35,learning_rate=0.1,max_bin=255,max_depth=-1)
model_.fit(OH_X_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_bin=255,
               max_depth=-1, min_child_samples=20, min_child_weight=0.001,
               min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=35,
               objective=None, random_state=None, reg_alpha=0.0, reg_lambda=0.0,
               silent=True, subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0)

In [34]:
pred_lgm=model_.predict(OH_X_valid)


In [35]:
x_lgm=accuracy_score(y_test,pred_lgm)
print(f'the accuracy score is {x_lgm}')

the accuracy score is 0.9883824843610366


In [44]:
cm= confusion_matrix(y_test,pred_lgm)
print(cm)

[[1040   14]
 [  12 1172]]


Bagged Decision Tree

In [37]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
clf_ = BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=200,n_jobs=5).fit(OH_X_train,y_train)
pred_bag=clf_.predict(OH_X_valid)
x_bag=accuracy_score(y_test,pred_bag)
print(f'the accuracy score is {x_bag}')

the accuracy score is 0.985254691689008


In [45]:
cm= confusion_matrix(y_test,pred_bag)
print(cm)

[[1030   24]
 [   9 1175]]


Bagged Light GBM

In [38]:
from sklearn.ensemble import BaggingClassifier
clf_2 = BaggingClassifier(base_estimator= LGBMClassifier(), n_estimators=270,random_state=50).fit(OH_X_train,y_train)
pred_bag_=clf_2.predict(OH_X_valid)
x_bag_=accuracy_score(y_test,pred_bag_)
print(f'the accuracy score is {x_bag_}')

the accuracy score is 0.9892761394101877


In [46]:
cm= confusion_matrix(y_test,pred_bag_)
print(cm)

[[1043   11]
 [  19 1165]]


Bagged Catboost

In [48]:
from sklearn.ensemble import BaggingClassifier

clf_3 = BaggingClassifier(base_estimator= CatBoostClassifier(), n_estimators=40,random_state=50).fit(OH_X_train,y_train)
pred_bag_c=clf_3.predict(OH_X_valid)
x_bag_c=accuracy_score(y_test,pred_bag_c)
print(f'the accuracy score is {x_bag_c}')

Streaming output truncated to the last 5000 lines.
5:	learn: 0.6092849	total: 25.1ms	remaining: 4.17s
6:	learn: 0.5944030	total: 29.2ms	remaining: 4.14s
7:	learn: 0.5818183	total: 33.2ms	remaining: 4.12s
8:	learn: 0.5708041	total: 37.1ms	remaining: 4.09s
9:	learn: 0.5592284	total: 39.4ms	remaining: 3.9s
10:	learn: 0.5483393	total: 43.2ms	remaining: 3.89s
11:	learn: 0.5378218	total: 47.2ms	remaining: 3.89s
12:	learn: 0.5282937	total: 51.1ms	remaining: 3.88s
13:	learn: 0.5166672	total: 54.9ms	remaining: 3.87s
14:	learn: 0.5062226	total: 58.8ms	remaining: 3.86s
15:	learn: 0.4960053	total: 62.9ms	remaining: 3.87s
16:	learn: 0.4857507	total: 67.1ms	remaining: 3.88s
17:	learn: 0.4761487	total: 71.2ms	remaining: 3.88s
18:	learn: 0.4685619	total: 83.8ms	remaining: 4.33s
19:	learn: 0.4600080	total: 86.5ms	remaining: 4.24s
20:	learn: 0.4520414	total: 90.4ms	remaining: 4.21s
21:	learn: 0.4427115	total: 94.4ms	remaining: 4.2s
22:	learn: 0.4379999	total: 95.5ms	remaining: 4.06s
23:	learn: 0.4300115

In [49]:
cm= confusion_matrix(y_test,pred_bag_c)
print(cm)

[[1043   11]
 [  19 1165]]
