# K-Nearest-Neighbors (KNN)


## Importing Libraries

In [ ]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

Installing Dependencies

In [ ]:
!pip install lightgbm
!pip install xgboost

#Importing the data
## About the data

<img src='https://images.squarespace-cdn.com/content/v1/5c36736d9d5abb8b44c6b7f7/1586468701075-G14EXPZE2VNMJFKDCQ0T/rook+and+king+logo.jpg?format=500w' align="center"><br>
  Chess End-Game -- King+Rook versus King+Pawn on a7
  (usually abbreviated KRKPA7).  The pawn on a7 means it is one square
  away from queening.  It is the King+Rook's side (white) to move.

  

In [ ]:
os.chdir('/content/sample_data/')

In [ ]:
king_data=pd.read_excel('/content/sample_data/King-RookvsKing-Pawn.xlsx')

In [ ]:
king_data.head(10)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0       f       f       f       f  ...        t        t        n      won
1       f       f       f       f  ...        t        t        n      won
2       f       f       f       f  ...        t        t        n      won
3       f       f       f       f  ...        t        t        n      won
4       f       f       f       f  ...        t        t        n      won
5       f       f       f       f  ...        t        t        n      won
6       f       f       f       f  ...        t        t        n      won
7       f       f       f       f  ...        t        t        n      won
8       f       f       f       f  ...        t        t        n      won
9       f       f       f       f  ...        t        t        n      won

[10 rows x 37 columns]

In [ ]:
king_data.columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 'Column24',
       'Column25', 'Column26', 'Column27', 'Column28', 'Column29', 'Column30',
       'Column31', 'Column32', 'Column33', 'Column34', 'Column35', 'Column36',
       'Column37'],
      dtype='object')

In [ ]:
object_col=['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 'Column24',
       'Column25', 'Column26', 'Column27', 'Column28', 'Column29', 'Column30',
       'Column31', 'Column32', 'Column33', 'Column34', 'Column35', 'Column36'
       ]

Droping NaN values

In [ ]:
king_data.dropna(axis=0)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0          f       f       f       f  ...        t        t        n      won
1          f       f       f       f  ...        t        t        n      won
2          f       f       f       f  ...        t        t        n      won
3          f       f       f       f  ...        t        t        n      won
4          f       f       f       f  ...        t        t        n      won
...      ...     ...     ...     ...  ...      ...      ...      ...      ...
3191       t       f       f       f  ...        t        f        n    nowin
3192       t       f       f       f  ...        t        f        n    nowin
3193       t       f       f       f  ...        t        f        n    nowin
3194       t       f       t       f  ...        f        f        n    nowin
3195       t       f       t       f  ...        f        f        n    nowin

[3196 rows x 37 columns]

In [ ]:
print(f'{king_data.Column37.unique()}')

['won' 'nowin']


In [ ]:
king_data['Column37']=king_data['Column37'].apply({'won':2,'nowin':1}.get)

In [ ]:
king_data.head(10)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0       f       f       f       f  ...        t        t        n        2
1       f       f       f       f  ...        t        t        n        2
2       f       f       f       f  ...        t        t        n        2
3       f       f       f       f  ...        t        t        n        2
4       f       f       f       f  ...        t        t        n        2
5       f       f       f       f  ...        t        t        n        2
6       f       f       f       f  ...        t        t        n        2
7       f       f       f       f  ...        t        t        n        2
8       f       f       f       f  ...        t        t        n        2
9       f       f       f       f  ...        t        t        n        2

[10 rows x 37 columns]

## Spliting the data.

In [ ]:
X=king_data.copy()
y=X.pop('Column37')

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,train_size=0.3)


In [ ]:
y_test.head(10)

93      2
2848    1
2386    1
260     2
1748    2
1445    1
2603    1
473     2
1773    2
1274    1
Name: Column37, dtype: int64

## Training and predicting the model using different classification algo.



In [ ]:
from sklearn.preprocessing import OneHotEncoder
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)

one_hot_train=pd.DataFrame(OH_encoder.fit_transform(X_train[object_col]))
one_hot_test=pd.DataFrame(OH_encoder.transform(X_test[object_col]))
one_hot_train.index = X_train.index
one_hot_test.index = X_test.index

In [ ]:
num_X_train = X_train.drop(object_col, axis=1)
num_X_valid = X_test.drop(object_col, axis=1)

In [ ]:
OH_X_train = pd.concat([num_X_train, one_hot_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, one_hot_test], axis=1)

In [ ]:
y_train.unique()

array([1, 2])

#Classification Algorithms

##1. KNN Algorithm

In [ ]:
from sklearn.neighbors import KNeighborsClassifier as knn

model=knn(n_neighbors=1,
          leaf_size=1,
          algorithm='brute',
          weights='distance',
          p=1
          )

model.fit(OH_X_train,y_train)

KNeighborsClassifier(algorithm='brute', leaf_size=1, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=1,
                     weights='distance')

In [ ]:

pred=model.predict(OH_X_valid)

## Checking model accuracy.


In [ ]:
from sklearn.metrics import accuracy_score

x=accuracy_score(y_test,pred)
print(f'the accuracy score is {x}')

the accuracy score is 0.8856121537086684


## Using confusion matric

In [ ]:
from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_test,pred)

In [ ]:
print(cm)

[[ 949  119]
 [ 137 1033]]


##2. XgBoost Classifier

In [ ]:
import xgboost as xgb
model=xgb.XGBClassifier(n_estimators=400, random_state=42)
model.fit(OH_X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=400, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:

pred=model.predict(OH_X_valid)

## Checking model accuracy.


In [ ]:
from sklearn.metrics import accuracy_score

x=accuracy_score(y_test,pred)
print(f'the accuracy score is {x}')

the accuracy score is 0.9848078641644326


## Using confusion matric

In [ ]:
from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_test,pred)

In [ ]:
print(cm)

[[1056   12]
 [  22 1148]]


##3. LightGBM Classifier

In [ ]:
import lightgbm as lgb
model=lgb.LGBMClassifier(n_estimators=200,random_state=42)
model.fit(OH_X_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=200, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:

pred=model.predict(OH_X_valid)

## Checking model accuracy.


In [ ]:
from sklearn.metrics import accuracy_score

x=accuracy_score(y_test,pred)
print(f'the accuracy score is {x}')

the accuracy score is 0.9901697944593387


## Using confusion matric

In [ ]:
from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_test,pred)

In [ ]:
print(cm)

[[1060    8]
 [  14 1156]]
