# K-Nearest-Neighbors (KNN)


## Importing Libraries

In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

#Importing the data
## About the data

<img src='https://images.squarespace-cdn.com/content/v1/5c36736d9d5abb8b44c6b7f7/1586468701075-G14EXPZE2VNMJFKDCQ0T/rook+and+king+logo.jpg?format=500w' align="center"><br>
  Chess End-Game -- King+Rook versus King+Pawn on a7
  (usually abbreviated KRKPA7).  The pawn on a7 means it is one square
  away from queening.  It is the King+Rook's side (white) to move.

  

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_excel('/content/drive/MyDrive/hacktober/King-RookvsKing-Pawn.xlsx')

In [6]:
king_data = df
# king_data=pd.read_excel('King-Rook vs. King-Pawn.xlsx')

In [7]:
king_data.head(10)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0       f       f       f       f  ...        t        t        n      won
1       f       f       f       f  ...        t        t        n      won
2       f       f       f       f  ...        t        t        n      won
3       f       f       f       f  ...        t        t        n      won
4       f       f       f       f  ...        t        t        n      won
5       f       f       f       f  ...        t        t        n      won
6       f       f       f       f  ...        t        t        n      won
7       f       f       f       f  ...        t        t        n      won
8       f       f       f       f  ...        t        t        n      won
9       f       f       f       f  ...        t        t        n      won

[10 rows x 37 columns]

In [8]:
king_data.columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 'Column24',
       'Column25', 'Column26', 'Column27', 'Column28', 'Column29', 'Column30',
       'Column31', 'Column32', 'Column33', 'Column34', 'Column35', 'Column36',
       'Column37'],
      dtype='object')

In [9]:
object_col=['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 'Column24',
       'Column25', 'Column26', 'Column27', 'Column28', 'Column29', 'Column30',
       'Column31', 'Column32', 'Column33', 'Column34', 'Column35', 'Column36'
       ]

Droping NaN values

In [10]:
king_data.dropna(axis=0)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0          f       f       f       f  ...        t        t        n      won
1          f       f       f       f  ...        t        t        n      won
2          f       f       f       f  ...        t        t        n      won
3          f       f       f       f  ...        t        t        n      won
4          f       f       f       f  ...        t        t        n      won
...      ...     ...     ...     ...  ...      ...      ...      ...      ...
3191       t       f       f       f  ...        t        f        n    nowin
3192       t       f       f       f  ...        t        f        n    nowin
3193       t       f       f       f  ...        t        f        n    nowin
3194       t       f       t       f  ...        f        f        n    nowin
3195       t       f       t       f  ...        f        f        n    nowin

[3196 rows x 37 columns]

In [11]:
print(f'{king_data.Column37.unique()}')

['won' 'nowin']


In [12]:
king_data['Column37']=king_data['Column37'].apply({'won':2,'nowin':1}.get)

In [13]:
king_data.head(10)

Column1 Column2 Column3 Column4  ... Column34 Column35 Column36 Column37
0       f       f       f       f  ...        t        t        n        2
1       f       f       f       f  ...        t        t        n        2
2       f       f       f       f  ...        t        t        n        2
3       f       f       f       f  ...        t        t        n        2
4       f       f       f       f  ...        t        t        n        2
5       f       f       f       f  ...        t        t        n        2
6       f       f       f       f  ...        t        t        n        2
7       f       f       f       f  ...        t        t        n        2
8       f       f       f       f  ...        t        t        n        2
9       f       f       f       f  ...        t        t        n        2

[10 rows x 37 columns]

## Spliting the data.

In [14]:
X=king_data.copy()
y=X.pop('Column37')

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,train_size=0.3)


In [15]:
y_test.head(10)

2762    1
2454    1
2120    2
2629    1
924     1
2137    2
2591    1
2112    2
2838    1
626     2
Name: Column37, dtype: int64

## Training and predicting the model using KNN algo.



In [16]:
from sklearn.preprocessing import OneHotEncoder
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)

one_hot_train=pd.DataFrame(OH_encoder.fit_transform(X_train[object_col]))
one_hot_test=pd.DataFrame(OH_encoder.transform(X_test[object_col]))
one_hot_train.index = X_train.index
one_hot_test.index = X_test.index

In [17]:
num_X_train = X_train.drop(object_col, axis=1)
num_X_valid = X_test.drop(object_col, axis=1)

In [18]:
OH_X_train = pd.concat([num_X_train, one_hot_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, one_hot_test], axis=1)

In [19]:
y_train.unique()

array([1, 2])

In [20]:
from sklearn.neighbors import KNeighborsClassifier as knn

model=knn(n_neighbors=1,
          leaf_size=1,
          algorithm='brute',
          weights='distance',
          p=1
          )

model.fit(OH_X_train,y_train)

KNeighborsClassifier(algorithm='brute', leaf_size=1, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=1,
                     weights='distance')

In [21]:
pred=model.predict(OH_X_valid)

## Checking model accuracy.


In [40]:
from sklearn.metrics import accuracy_score

x=accuracy_score(y_test,pred)
print(f'the accuracy score is {x}')

the accuracy score is 0.8672922252010724


# Confusion Matrix

In [41]:
from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_test,pred)

In [42]:
print(cm)

[[ 909  164]
 [ 133 1032]]


# Trying Other Classifiction Algorithm :
- Decision Tree 
- Random Forest
- Naive Bayes
- Support Vector Machine

In [25]:
from sklearn.model_selection import GridSearchCV    # for getting the best hyperparameters
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [45]:
model_params  = {    
    "svm" : {
        "model":SVC(gamma="auto"),
        "params":{
            'C' : [1,10,20],
            'kernel':["rbf"]
        }
    },
    
    "decision_tree":{
        "model": DecisionTreeClassifier(random_state=0),
        "params":{
            'criterion':["entropy","gini"],
            "max_depth":[5,8,9]
        }
    },
    
    "random_forest":{
        "model": RandomForestClassifier(random_state=0),
        "params":{
            "n_estimators":[1,5,10],
            "max_depth":[5,8,9,10]
        }
    },
    "naive_bayes":{
        "model": GaussianNB(),
        "params":{}
    }
}

In [27]:
score=[]
for model_name,mp in model_params.items():
    clf = GridSearchCV(mp["model"],mp["params"],cv=4,return_train_score=False)
    clf.fit(OH_X_train,y_train)
    score.append({
        "Model" : model_name,
        "Best_Score": clf.best_score_,
        "Best_Params": clf.best_params_
    })

In [28]:
result = pd.DataFrame(score,columns=["Model","Best_Score","Best_Params"])

In [29]:
result

Model  Best_Score                               Best_Params
0            svm    0.961376                {'C': 20, 'kernel': 'rbf'}
1  decision_tree    0.978060  {'criterion': 'entropy', 'max_depth': 9}
2  random_forest    0.970764     {'max_depth': 10, 'n_estimators': 10}
3    naive_bayes    0.603347                                        {}

`In above cases, we get the decision tree to give the best_score on the training set, so we will try using cross validation on a decision tree algorithm as below:`

In [46]:
from sklearn.model_selection import cross_val_score    # cross validating 

clf_dt = DecisionTreeClassifier(max_depth= 9, criterion= 'entropy', random_state=1)
scores = cross_val_score(clf_dt,OH_X_train,y_train,cv=8,scoring="accuracy")

In [49]:
scores.mean()*100

98.015581232493

In [38]:
clf_dt.fit(OH_X_train,y_train)
y_pred = clf_dt.predict(OH_X_valid)

## Accuracy Score by Decision Tree

In [39]:
 # accuracy score by decision tree
acc = accuracy_score(y_test,y_pred)       
print(acc*100)

98.39142091152814


## Confusion Matric Scores by Decision Tree

In [44]:
dcm= confusion_matrix(y_test,y_pred)
dcm

array([[1047,   26],
       [  10, 1155]])